solution for 03/03-04
js-tasks-ru/nodejs-20210618_anton-shafner pull request #4
Opened 2022-02-01 14:10 UTC by dragooon4ik24

Нужна помощь. Некоторые тесты почему то не проходят, хотя при ручном тестировании всё отрабатывает

2022-02-01 20:10 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-01 20:36 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-04 19:30 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-04 19:32 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-05 11:47 UTC, tadjik1 commented on 03-streams/04-file-server-post/server.js
> +      res.statusCode = 500;
сам по себе `req.on('close', ...)` свидетельствует лишь о том, что запрос был завершен. причем когда вы ниже вызываете `res.end()` - это тоже приводит к вызову этого обработчика. таким образом, вы дважды пытаетесь завершить запрос вызовом `res.end()` что и приводит к падению тестов.

вам надо первым делом избавиться от двойного вызова res.end(), сделать это можно несколькими способами - мне кажется проще всего отследить вложенные пути не в момент записи файла, а вообще до создания стримов, в момент обработки запроса. т.е. уже на 15 строке вы можете добавить условие
```
if (nestingLvl !== 0 && nestingLvl > 1) {
  res.statusCode = 400;
  res.end('Subfolders not supported');
  return;
}
```

2022-02-05 11:48 UTC, tadjik1 commented on 03-streams/04-file-server-post/server.js
> +            fs.unlinkSync(filepath, (err) => {
вместо `unlinkSync` тут наверное подразумевался `unlink`?

2022-02-05 11:48 UTC, tadjik1 requested changes
@dragooon4ik24 отписался по проблемам, надеюсь это поможет в решении :)

2022-02-06 15:37 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2022-02-07 08:41 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2022-02-08 16:15 UTC, tadjik1 approved these changes
@dragooon4ik24 отлично, все решено верно 🚀

2022-02-08 16:16 UTC, merged